ALTER TABLE users
    ADD COLUMN last_name VARCHAR(100) NOT NULL,
    ADD COLUMN first_name VARCHAR(100) NOT NULL,
    ADD COLUMN email VARCHAR(255) NOT NULL UNIQUE,
    ADD COLUMN phone VARCHAR(20) NOT NULL,
    ADD COLUMN region VARCHAR(100) NOT NULL;
