CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    phone VARCHAR(20) NOT NULL,
    ph DECIMAL(5,2) DEFAULT NULL,
    rain DECIMAL(5,2) DEFAULT NULL,
    humidity DECIMAL(5,2) DEFAULT NULL,
    soil_humidity DECIMAL(5,2) DEFAULT NULL,
    light DECIMAL(5,2) DEFAULT NULL,
    valve_open TINYINT(1) NOT NULL DEFAULT 0,
    valve_angle INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
